name: CI Workflow

on: 
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Install bsdtar for pacman package creation
      run: sudo apt-get update && sudo apt-get install libarchive-tools -y

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Determine pre-release status and release name
      id: prep
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        if [ "$BRANCH_NAME" = "master" ]; then
          echo "RELEASE_NAME=v${{ github.event.repository_vesion }}" >> $GITHUB_ENV
          echo "PRE_RELEASE=false" >> $GITHUB_ENV
        else
          echo "RELEASE_NAME=v${{ github.event.repository_vesion }}-$BRANCH_NAME" >> $GITHUB_ENV
          echo "PRE_RELEASE=true" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      run: |
        cd electrb
        npm install

    - name: Build and package
      run: |
        cd electrb
        npm run dist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: electrb-build-${{ github.ref_name }}
        path: |
          electrb/dist/electrb-${{ github.ref_name }}*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: ${{ env.PRE_RELEASE }}
